services:
  browser:
    build:
      context: .
    image: grindev1996/browser-container:latest
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    image: kennethreitz/httpbin
    ports:
      - "5000:80"
