version: '3.8'

services:
  browser:
    build:
      context: .
    depends_on:
      - backend
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"